### ISSUE TITLE
design philosophy clarification

### ISSUE THREAD

**Issue by odanoburu** [lexi-lambda/megaparsack#18]
I was thinking of adding a few new parsers, as I'm doing for `any-char/p`, so I'm wondering what's `megaparsack`'s design philosophy -- would you rather keep the package minimal, or provide convenience parsers that can easily be defined, but would otherwise end up being repeated by several users, or something in-between? I'm currently thinking of dumb parsers like `newline/p`, `crlf/p`, `eol/p`, but I may think of others!

**Comment by lexi-lambda** [comment]
I think having batteries is a good thing, to a point. I don’t think megaparsack needs to include every parser under the sun, but I don’t think adding some like the ones you mention would be a bad thing.

**Comment by odanoburu** [comment]
ok, that makes sense! I'll see if I have new parsers that I think worthwhile to add and open another PR.
