### ISSUE TITLE
Parser request: value/p

### ISSUE THREAD

**Issue by countvajhula** [lexi-lambda/megaparsack#32]
A parser `value/p` that succeeds and returns a provided value, without consuming any input.

An example where it would be handy is the following, where we expect that the input _may_ contain something, say a sequence, but if absent, that's still OK and we'd want to use a default value for it in that case:
```
(do [name <- name/p]
    [schools <- (or/p (try/p sequence-parser/p)
                      (value/p null))]
    (pure (list name schools)))
```

The actual context where this suggested itself was in [this parser](https://github.com/countvajhula/social-contract/blob/c2e69d7c27468e6bfbb71f9f3f435cef5966b443/contract/social/c3po/contract-parser.rkt#L341-L343), where if a `value/p` were available, I could have avoided writing the "with" and "without" parsers and then `or/p`ing over them in a third parser, and instead have had a single parser with an optional step and a default value.

**Comment by lexi-lambda** [comment]
This is exactly what `pure` is: in this case, you could use `(pure null)` in place of `(value/p null)` to get the behavior you want.

Let me know if I’ve misunderstood something, and that doesn’t work, but otherwise I think I am going to close this issue.

**Comment by countvajhula** [comment]
Ah, of course. Thanks!
