### ISSUE TITLE
Alternating String Parser

### ISSUE THREAD

**Issue by abhillman** [lexi-lambda/megaparsack#34]
I'm not certain if this is a bug, but can't readily think of what might be wrong with this example:

```racket
> (require megaparsack megaparsack/text)
> (parse-result! (parse-string (many+/p (or (try/p (string/p "ab")) (string/p "xy"))) "xy"))
string:1:0: parse error
  unexpected: x
  expected: ab
 [,bt for context]
```

By contrast, a similar example with `parsack`:

```racket
> (require parsack)
> (parse (many1 (<or> (string "ab") (string "xy"))) "ab")
(Consumed (Ok '(#\a #\b)))
> (parse (many1 (<or> (string "ab") (string "xy"))) "xy")
(Consumed (Ok '(#\x #\y)))
> (parse (many1 (<or> (string "ab") (string "xy"))) "xyab")
(Consumed (Ok '((#\x #\y) (#\a #\b))))
```

**Comment by lexi-lambda** [comment]
A bit late, I imagine, but the issue here is that you have mistakenly written `or` instead of `or/p`. It is unfortunate that this is such an easy mistake to make and so difficult to catch, but such is the nature of such a flexible `or` operation.
