### ISSUE TITLE
Feature request: `char-between/p` and `char-in/p`

### ISSUE THREAD

**Issue by jackfirth** [lexi-lambda/megaparsack#5]
These are simple utilities for parsing character ranges:

```racket
(define ascii-digit/p (char-between/p #\0 #\1))
(define ascii-vowel/p (char-in/p "aeiou"))
```

As with #3 and #4, I've implemented these and wanted to know if they'd be welcomed in `megaparsack/text`

**Comment by lexi-lambda** [comment]
Resolved by 245950a24edc3688b7819915afad34888c1525b2.
